name: Test And Build BOT
on:
  push:
    paths-ignore:
      - ".github/**"
      - ".devcontainer/**"
    branches-ignore:
      - "renovate/**"
  pull_request:
    branches-ignore:
      - "renovate/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CheckFiles: "launcher.py cogs/"

    steps:
      - uses: actions/checkout@v3.0.0
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v3.1.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --select=E9,F63,F7,F82 --show-source

      - name: Check with Isort
        run: |
          pip install isort
          isort --check --sp setup.cfg $CheckFiles

      - name: Sort with Isort
        if: failure()
        run: |
          isort --sp setup.cfg $CheckFiles

      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v4.0.1
        with:
          branch: actions/auto
          commit-message: Changes done by tests
          title: Linter changed files

  build-and-push-container:
    if: github.event_name != 'pull_request' && contains(github.ref, 'actions') != 'true'
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0
      - name: Create VARS
        id: vars
        run: |
          echo "::set-output name=branch::${GITHUB_REF//refs\/heads\//}"
          echo "::set-output name=username::$(echo ${GITHUB_REPOSITORY} | cut -d/ -f1 | tr '[:upper:]' '[:lower:]')"
          echo "::set-output name=source::${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/tree/${GITHUB_REF//refs\/heads\//}"
          echo "::set-output name=url::${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/blob/master/README.md"
          echo "::set-output name=tag::$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]'):${GITHUB_SHA}"
          echo "::set-output name=bot_ver::$(cat cogs/utils/Bot_version.py | cut -d'"' -f 2)"

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ steps.vars.outputs.username }}
      #     password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ steps.vars.outputs.username }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: ${{ steps.vars.outputs.platform }}
          file: ./amd64.Dockerfile
          tags: |
            ghcr.io/${{ steps.vars.outputs.tag }}
          labels: |
            org.opencontainers.image.source=${{ steps.vars.outputs.source }}
            org.opencontainers.image.url=${{ steps.vars.outputs.url }}

      - name: Create manifests for GitHub Container Registry
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          IMAGE=ghcr.io/$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')
          SOURCE=${IMAGE}:${GITHUB_SHA}
          docker manifest create ${IMAGE}:${{ steps.vars.outputs.branch }}    --amend ${SOURCE} && docker manifest push ${IMAGE}:${{ steps.vars.outputs.branch }}
          if [[ ${GITHUB_REF//refs\/heads\//} == master ]]; then
            docker manifest create ${IMAGE}:${{ steps.vars.outputs.bot_ver }} --amend ${SOURCE} && docker manifest push ${IMAGE}:${{ steps.vars.outputs.bot_ver }}
            docker manifest create ${IMAGE}:latest                            --amend ${SOURCE} && docker manifest push ${IMAGE}:latest
          fi
